// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/service.proto

package lumenvecpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorService_Health_FullMethodName          = "/lumenvec.VectorService/Health"
	VectorService_ListVectors_FullMethodName     = "/lumenvec.VectorService/ListVectors"
	VectorService_AddVector_FullMethodName       = "/lumenvec.VectorService/AddVector"
	VectorService_AddVectorsBatch_FullMethodName = "/lumenvec.VectorService/AddVectorsBatch"
	VectorService_GetVector_FullMethodName       = "/lumenvec.VectorService/GetVector"
	VectorService_Search_FullMethodName          = "/lumenvec.VectorService/Search"
	VectorService_SearchBatch_FullMethodName     = "/lumenvec.VectorService/SearchBatch"
	VectorService_DeleteVector_FullMethodName    = "/lumenvec.VectorService/DeleteVector"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ListVectors(ctx context.Context, in *ListVectorsRequest, opts ...grpc.CallOption) (*ListVectorsResponse, error)
	AddVector(ctx context.Context, in *AddVectorRequest, opts ...grpc.CallOption) (*AddVectorResponse, error)
	AddVectorsBatch(ctx context.Context, in *AddVectorsBatchRequest, opts ...grpc.CallOption) (*AddVectorsBatchResponse, error)
	GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (*SearchBatchResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, VectorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ListVectors(ctx context.Context, in *ListVectorsRequest, opts ...grpc.CallOption) (*ListVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVectorsResponse)
	err := c.cc.Invoke(ctx, VectorService_ListVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) AddVector(ctx context.Context, in *AddVectorRequest, opts ...grpc.CallOption) (*AddVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_AddVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) AddVectorsBatch(ctx context.Context, in *AddVectorsBatchRequest, opts ...grpc.CallOption) (*AddVectorsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVectorsBatchResponse)
	err := c.cc.Invoke(ctx, VectorService_AddVectorsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_GetVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, VectorService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (*SearchBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBatchResponse)
	err := c.cc.Invoke(ctx, VectorService_SearchBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility.
type VectorServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ListVectors(context.Context, *ListVectorsRequest) (*ListVectorsResponse, error)
	AddVector(context.Context, *AddVectorRequest) (*AddVectorResponse, error)
	AddVectorsBatch(context.Context, *AddVectorsBatchRequest) (*AddVectorsBatchResponse, error)
	GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorServiceServer struct{}

func (UnimplementedVectorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVectorServiceServer) ListVectors(context.Context, *ListVectorsRequest) (*ListVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVectors not implemented")
}
func (UnimplementedVectorServiceServer) AddVector(context.Context, *AddVectorRequest) (*AddVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVector not implemented")
}
func (UnimplementedVectorServiceServer) AddVectorsBatch(context.Context, *AddVectorsBatchRequest) (*AddVectorsBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVectorsBatch not implemented")
}
func (UnimplementedVectorServiceServer) GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVector not implemented")
}
func (UnimplementedVectorServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectorServiceServer) SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchBatch not implemented")
}
func (UnimplementedVectorServiceServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}
func (UnimplementedVectorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	// If the following call panics, it indicates UnimplementedVectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ListVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ListVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ListVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ListVectors(ctx, req.(*ListVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_AddVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).AddVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_AddVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).AddVector(ctx, req.(*AddVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_AddVectorsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVectorsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).AddVectorsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_AddVectorsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).AddVectorsBatch(ctx, req.(*AddVectorsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_GetVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).GetVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_GetVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).GetVector(ctx, req.(*GetVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_SearchBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).SearchBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_SearchBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).SearchBatch(ctx, req.(*SearchBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lumenvec.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _VectorService_Health_Handler,
		},
		{
			MethodName: "ListVectors",
			Handler:    _VectorService_ListVectors_Handler,
		},
		{
			MethodName: "AddVector",
			Handler:    _VectorService_AddVector_Handler,
		},
		{
			MethodName: "AddVectorsBatch",
			Handler:    _VectorService_AddVectorsBatch_Handler,
		},
		{
			MethodName: "GetVector",
			Handler:    _VectorService_GetVector_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _VectorService_Search_Handler,
		},
		{
			MethodName: "SearchBatch",
			Handler:    _VectorService_SearchBatch_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _VectorService_DeleteVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/service.proto",
}
