// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/proto/service.proto

package lumenvecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_api_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type AddVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVectorRequest) Reset() {
	*x = AddVectorRequest{}
	mi := &file_api_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorRequest) ProtoMessage() {}

func (x *AddVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorRequest.ProtoReflect.Descriptor instead.
func (*AddVectorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddVectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddVectorRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type AddVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVectorResponse) Reset() {
	*x = AddVectorResponse{}
	mi := &file_api_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorResponse) ProtoMessage() {}

func (x *AddVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorResponse.ProtoReflect.Descriptor instead.
func (*AddVectorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddVectorsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVectorsBatchRequest) Reset() {
	*x = AddVectorsBatchRequest{}
	mi := &file_api_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVectorsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorsBatchRequest) ProtoMessage() {}

func (x *AddVectorsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorsBatchRequest.ProtoReflect.Descriptor instead.
func (*AddVectorsBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddVectorsBatchRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type AddVectorsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVectorsBatchResponse) Reset() {
	*x = AddVectorsBatchResponse{}
	mi := &file_api_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVectorsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorsBatchResponse) ProtoMessage() {}

func (x *AddVectorsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorsBatchResponse.ProtoReflect.Descriptor instead.
func (*AddVectorsBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddVectorsBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVectorRequest) Reset() {
	*x = GetVectorRequest{}
	mi := &file_api_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVectorRequest) ProtoMessage() {}

func (x *GetVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVectorRequest.ProtoReflect.Descriptor instead.
func (*GetVectorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetVectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *Vector                `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVectorResponse) Reset() {
	*x = GetVectorResponse{}
	mi := &file_api_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVectorResponse) ProtoMessage() {}

func (x *GetVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVectorResponse.ProtoReflect.Descriptor instead.
func (*GetVectorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetVectorResponse) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchBatchQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchQuery) Reset() {
	*x = SearchBatchQuery{}
	mi := &file_api_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchQuery) ProtoMessage() {}

func (x *SearchBatchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchQuery.ProtoReflect.Descriptor instead.
func (*SearchBatchQuery) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchBatchQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchBatchQuery) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SearchBatchQuery) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*SearchBatchQuery    `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchRequest) Reset() {
	*x = SearchBatchRequest{}
	mi := &file_api_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchRequest) ProtoMessage() {}

func (x *SearchBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchRequest.ProtoReflect.Descriptor instead.
func (*SearchBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *SearchBatchRequest) GetQueries() []*SearchBatchQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type SearchBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchResult) Reset() {
	*x = SearchBatchResult{}
	mi := &file_api_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchResult) ProtoMessage() {}

func (x *SearchBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchResult.ProtoReflect.Descriptor instead.
func (*SearchBatchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchBatchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchBatchResult) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchBatchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchResponse) Reset() {
	*x = SearchBatchResponse{}
	mi := &file_api_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchResponse) ProtoMessage() {}

func (x *SearchBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchResponse.ProtoReflect.Descriptor instead.
func (*SearchBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *SearchBatchResponse) GetResults() []*SearchBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type DeleteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorRequest) Reset() {
	*x = DeleteVectorRequest{}
	mi := &file_api_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorRequest) ProtoMessage() {}

func (x *DeleteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteVectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorResponse) Reset() {
	*x = DeleteVectorResponse{}
	mi := &file_api_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorResponse) ProtoMessage() {}

func (x *DeleteVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorResponse.ProtoReflect.Descriptor instead.
func (*DeleteVectorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_service_proto protoreflect.FileDescriptor

const file_api_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/service.proto\x12\blumenvec\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"0\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\":\n" +
	"\x10AddVectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\"-\n" +
	"\x11AddVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x16AddVectorsBatchRequest\x12*\n" +
	"\avectors\x18\x01 \x03(\v2\x10.lumenvec.VectorR\avectors\"3\n" +
	"\x17AddVectorsBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\x10GetVectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11GetVectorResponse\x12(\n" +
	"\x06vector\x18\x01 \x01(\v2\x10.lumenvec.VectorR\x06vector\"<\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"B\n" +
	"\x0eSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.lumenvec.SearchResultR\aresults\"O\n" +
	"\x10SearchBatchQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"J\n" +
	"\x12SearchBatchRequest\x124\n" +
	"\aqueries\x18\x01 \x03(\v2\x1a.lumenvec.SearchBatchQueryR\aqueries\"U\n" +
	"\x11SearchBatchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\aresults\x18\x02 \x03(\v2\x16.lumenvec.SearchResultR\aresults\"L\n" +
	"\x13SearchBatchResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.lumenvec.SearchBatchResultR\aresults\":\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\"%\n" +
	"\x13DeleteVectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x88\x04\n" +
	"\rVectorService\x12;\n" +
	"\x06Health\x12\x17.lumenvec.HealthRequest\x1a\x18.lumenvec.HealthResponse\x12D\n" +
	"\tAddVector\x12\x1a.lumenvec.AddVectorRequest\x1a\x1b.lumenvec.AddVectorResponse\x12V\n" +
	"\x0fAddVectorsBatch\x12 .lumenvec.AddVectorsBatchRequest\x1a!.lumenvec.AddVectorsBatchResponse\x12D\n" +
	"\tGetVector\x12\x1a.lumenvec.GetVectorRequest\x1a\x1b.lumenvec.GetVectorResponse\x12;\n" +
	"\x06Search\x12\x17.lumenvec.SearchRequest\x1a\x18.lumenvec.SearchResponse\x12J\n" +
	"\vSearchBatch\x12\x1c.lumenvec.SearchBatchRequest\x1a\x1d.lumenvec.SearchBatchResponse\x12M\n" +
	"\fDeleteVector\x12\x1d.lumenvec.DeleteVectorRequest\x1a\x1e.lumenvec.DeleteVectorResponseB\x1fZ\x1dlumenvec/api/proto;lumenvecpbb\x06proto3"

var (
	file_api_proto_service_proto_rawDescOnce sync.Once
	file_api_proto_service_proto_rawDescData []byte
)

func file_api_proto_service_proto_rawDescGZIP() []byte {
	file_api_proto_service_proto_rawDescOnce.Do(func() {
		file_api_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)))
	})
	return file_api_proto_service_proto_rawDescData
}

var file_api_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_service_proto_goTypes = []any{
	(*HealthRequest)(nil),           // 0: lumenvec.HealthRequest
	(*HealthResponse)(nil),          // 1: lumenvec.HealthResponse
	(*Vector)(nil),                  // 2: lumenvec.Vector
	(*AddVectorRequest)(nil),        // 3: lumenvec.AddVectorRequest
	(*AddVectorResponse)(nil),       // 4: lumenvec.AddVectorResponse
	(*AddVectorsBatchRequest)(nil),  // 5: lumenvec.AddVectorsBatchRequest
	(*AddVectorsBatchResponse)(nil), // 6: lumenvec.AddVectorsBatchResponse
	(*GetVectorRequest)(nil),        // 7: lumenvec.GetVectorRequest
	(*GetVectorResponse)(nil),       // 8: lumenvec.GetVectorResponse
	(*SearchRequest)(nil),           // 9: lumenvec.SearchRequest
	(*SearchResponse)(nil),          // 10: lumenvec.SearchResponse
	(*SearchBatchQuery)(nil),        // 11: lumenvec.SearchBatchQuery
	(*SearchBatchRequest)(nil),      // 12: lumenvec.SearchBatchRequest
	(*SearchBatchResult)(nil),       // 13: lumenvec.SearchBatchResult
	(*SearchBatchResponse)(nil),     // 14: lumenvec.SearchBatchResponse
	(*SearchResult)(nil),            // 15: lumenvec.SearchResult
	(*DeleteVectorRequest)(nil),     // 16: lumenvec.DeleteVectorRequest
	(*DeleteVectorResponse)(nil),    // 17: lumenvec.DeleteVectorResponse
}
var file_api_proto_service_proto_depIdxs = []int32{
	2,  // 0: lumenvec.AddVectorsBatchRequest.vectors:type_name -> lumenvec.Vector
	2,  // 1: lumenvec.GetVectorResponse.vector:type_name -> lumenvec.Vector
	15, // 2: lumenvec.SearchResponse.results:type_name -> lumenvec.SearchResult
	11, // 3: lumenvec.SearchBatchRequest.queries:type_name -> lumenvec.SearchBatchQuery
	15, // 4: lumenvec.SearchBatchResult.results:type_name -> lumenvec.SearchResult
	13, // 5: lumenvec.SearchBatchResponse.results:type_name -> lumenvec.SearchBatchResult
	0,  // 6: lumenvec.VectorService.Health:input_type -> lumenvec.HealthRequest
	3,  // 7: lumenvec.VectorService.AddVector:input_type -> lumenvec.AddVectorRequest
	5,  // 8: lumenvec.VectorService.AddVectorsBatch:input_type -> lumenvec.AddVectorsBatchRequest
	7,  // 9: lumenvec.VectorService.GetVector:input_type -> lumenvec.GetVectorRequest
	9,  // 10: lumenvec.VectorService.Search:input_type -> lumenvec.SearchRequest
	12, // 11: lumenvec.VectorService.SearchBatch:input_type -> lumenvec.SearchBatchRequest
	16, // 12: lumenvec.VectorService.DeleteVector:input_type -> lumenvec.DeleteVectorRequest
	1,  // 13: lumenvec.VectorService.Health:output_type -> lumenvec.HealthResponse
	4,  // 14: lumenvec.VectorService.AddVector:output_type -> lumenvec.AddVectorResponse
	6,  // 15: lumenvec.VectorService.AddVectorsBatch:output_type -> lumenvec.AddVectorsBatchResponse
	8,  // 16: lumenvec.VectorService.GetVector:output_type -> lumenvec.GetVectorResponse
	10, // 17: lumenvec.VectorService.Search:output_type -> lumenvec.SearchResponse
	14, // 18: lumenvec.VectorService.SearchBatch:output_type -> lumenvec.SearchBatchResponse
	17, // 19: lumenvec.VectorService.DeleteVector:output_type -> lumenvec.DeleteVectorResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
		MessageInfos:      file_api_proto_service_proto_msgTypes,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}
